# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentoProtocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('experimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Experimento')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoExperimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('experimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Experimento')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.Proyecto')),
            ],
        ),
    ]
